eureka:
  client:
    service-url:
      defaultZone: http://domain-eureka:8761/eureka/

##将请求转发到对应模块进行处理
server:
  port: 9002
file:
  path: C:/Users/world/Desktop/i/
  domain: http://127.0.0.1:9000/file/f/

